site_name: EAE130 Aero-Code

theme:
  name: "material"

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["."]

nav:
  - Home: index.md
  - Reference: reference.md